
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 89
#define YY_END_OF_BUFFER 90
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[577] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   90,   89,   79,   80,
       89,   81,   84,   88,   88,   83,   82,   85,   86,   87,
       88,   88,   88,   88,   88,   88,   88,   88,   88,   88,
       88,   88,   88,   88,   88,    2,    2,    2,    4,    4,
        4,    6,    6,    6,   82,   88,   88,   46,   88,   88,
       47,   57,   57,   57,   70,   70,   70,   89,    8,    8,
        8,   89,   79,    0,   78,   81,   88,   82,   88,   82,
       88,   88,   88,   88,   88,   88,   88,   88,   88,   88,

       88,   88,   88,   88,   88,   88,   88,   88,   88,   88,
       88,   88,   88,   88,   88,   88,   88,   88,   88,   88,
       48,   49,   19,    2,    2,    2,    2,    4,    4,    4,
        4,    6,    6,    6,    6,   10,   10,   46,   88,   46,
       45,   44,   57,   57,   57,   57,   70,   70,   70,   70,
        0,   74,    8,    8,    8,    8,    0,   77,   88,   88,
       88,   88,   88,   88,   88,   88,   88,   88,   88,   88,
       88,   88,   88,   88,   88,   88,   61,   88,   88,   88,
       88,   88,   88,   88,   88,   88,   60,   88,   88,   88,
       88,   88,   88,   88,   88,   88,   88,   88,   88,   88,

       88,   88,   88,   88,   88,   88,    9,   88,   88,    5,
       88,   88,   88,   54,   88,   88,   88,   88,   88,   88,
       88,   88,   88,   88,    7,   88,   88,   88,   88,   88,
       88,   88,   88,   88,   88,   88,   17,   88,   88,   88,
       88,   88,   88,   88,   88,   42,   88,   88,   88,   88,
       88,   88,   88,   24,   23,   88,   88,   88,   88,   88,
       72,   88,   88,   88,   88,   88,   88,   88,   88,   88,
       88,   88,   18,   88,   71,   88,   88,   88,   88,   88,
       88,   88,   88,   88,   10,   88,   88,   88,   88,   88,
       88,   88,   88,   75,   88,   88,   88,   88,   88,   88,

       88,   88,   88,   88,   88,   88,   88,   88,   21,   88,
       12,   88,   88,   88,   88,   88,   88,   14,   73,   88,
       52,   88,   88,   88,   67,   11,   88,   88,   88,   62,
       88,   88,   66,   88,   76,   88,   88,   88,   69,   88,
       88,   88,   88,   88,   88,   88,   88,    3,   88,   88,
       88,   88,   16,   88,   53,   88,   65,   88,   88,   88,
       88,   88,   88,   64,   43,   55,   88,   88,   88,   88,
       88,   88,   88,   88,   88,   88,   58,   88,   63,   88,
       88,   88,   88,   88,   59,   88,   88,   88,   88,   88,
        1,   88,   88,   88,   88,   88,   88,   88,   88,   88,

       88,   88,   88,   50,   88,   88,   88,   88,   15,   88,
       88,   88,   88,   88,   88,   88,   88,   13,   88,   88,
       88,   88,   88,   88,   88,   88,   88,   26,   88,   68,
       88,   88,   88,   88,   29,   88,   88,   88,   36,   88,
       88,   20,   88,   88,   88,   88,   88,   88,   88,   88,
       88,   88,   22,   88,   88,   88,   88,   88,   88,   88,
       88,   88,   88,   88,   88,   88,   88,   88,   88,   88,
       88,   88,   56,   88,   88,   88,   88,   88,   88,   88,
       88,   88,   88,   88,   88,   88,   88,   88,   88,   88,
       88,   88,   31,   88,   88,   88,   88,   88,   88,   88,

       88,   88,   88,   88,   88,   88,   41,   88,   88,   33,
       88,   88,   51,   88,   88,   88,   88,   88,   88,   88,
       88,   88,   88,   88,   88,   88,   88,   88,   88,   88,
       88,   30,   88,   88,   88,   37,   27,   88,   88,   88,
       88,   25,   88,   32,   88,   88,   88,   34,   88,   88,
       88,   88,   88,   88,   88,   88,   88,   88,   88,   39,
       88,   28,   88,   88,   40,   88,   35,   88,   88,   88,
       88,   88,   88,   88,   38,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    5,    1,    1,    1,    1,    1,
        1,    1,    1,    6,    7,    8,    9,   10,   11,   12,
       10,   10,   13,   10,   10,   10,   10,   14,   15,    1,
        1,    1,    1,    1,   16,   17,   18,   19,   17,   17,
       20,   21,   20,   20,   20,   20,   22,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
        1,    1,    1,    1,   20,    1,   23,   24,   25,   26,

       27,   28,   29,   30,   31,   20,   32,   33,   34,   35,
       36,   37,   38,   39,   40,   41,   42,   43,   44,   45,
       46,   20,   47,    1,   48,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[49] =
    {   0,
        1,    1,    2,    1,    1,    1,    3,    3,    1,    3,
        3,    3,    3,    3,    1,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    1,    1
    } ;

static yyconst flex_int16_t yy_base[595] =
    {   0,
        0,   48,   76,    0,  117,  165,  213,  261,    0,    0,
      309,  357,  396,    0,  417,  457,  504,  552,  600,  648,
      984,  983,  696,  744,  982,  981,  984,  989,  981,  989,
      978,    0,  989,    0,    6,  989,   12,  989,  989,  989,
      959,    0,  955,    1,  934,    0,    4,  951,  941,    0,
      939,   26,   41,   13,   58,    0,   61,   67,    0,   71,
       77,    0,  123,  129,  785,  135,  139,  145,  952,  948,
      989,    0,  149,  171,    0,  175,  181,  969,    0,  185,
      191,  968,  969,  966,  989,    0,    0,  195,  219,  225,
      953,  942,   72,  926,  932,  932,  930,  932,  925,  938,

      920,  952,  951,  926,  214,  910,  920,  914,  916,  911,
      915,  127,   56,  916,  218,  910,   10,  911,  924,  917,
        0,    0,    0,    0,  237,  241,  267,    0,  271,  275,
      281,    0,  285,  289,  315,  321,  931,  293,  326,  332,
        0,    0,    0,  336,  340,  363,    0,  367,  371,  377,
      940,  989,    0,  381,  385,  423,  939,  989,  924,  902,
      904,  903,  908,  912,  913,  912,  908,  902,  907,  890,
      174,  907,  903,  895,   73,  900,  895,  889,  107,  917,
      892,  889,  893,  199,  891,  888,    0,  885,  881,  877,
      873,  883,  874,  886,  904,  903,  880,  804,    7,  881,

      868,  862,  878,  864,  857,  871,    0,  862,  392,    0,
      877,  873,  858,    0,  855,  861,  856,  855,  233,  868,
       98,  885,  851,  854,    0,  410,  858,  852,  860,  860,
      851,  842,  818,  817,  806,  811,    0,  797,  369,  799,
      823,  803,  805,  779,  787,    0,  772,  799,  778,  765,
      772,  760,  764,    0,    0,  749,  762,  756,  752,  757,
        0,  756,  747,  746,  754,  194,  753,  744,  739,  732,
      743,  750,    0,  767,    0,  745,  732,  731,  729,  728,
      741,  741,  739,  725,  750,  744,  749,  721,  719,  717,
      711,  716,  734,    0,  714,  726,  702,  710,  695,  712,

      711,  697,  690,  697,  691,  693,  701,  688,    0,  699,
      718,  697,  687,  697,  690,  690,  678,    0,    0,  679,
        0,  682,  675,  702,    0,  707,  683,  681,  683,  671,
      659,  680,    0,  667,    0,  645,  649,  664,    0,  653,
      664,  643,  651,  645,  640,  647,  650,    0,  647,  643,
      649,  636,    0,  633,    0,  668,    0,  279,  640,  648,
      633,  644,  647,    0,    0,    0,  638,  641,  626,  635,
      638,  641,  619,  628,  621,  610,    0,  610,  601,  611,
      614,  599,  616,  602,    0,  614,  593,  589,  600,  597,
        0,  605,  596,  591,  598,  601,  588,  599,  584,  590,

      584,  588,  582,    0,  586,  583,  577,  590,    0,  589,
      579,  568,  591,  590,  561,  556,  554,    0,  566,  561,
      564,  563,  582,  557,  554,  555,  546,  577,  576,    0,
      547,  416,  574,  573,    0,  540,  537,  570,    0,  417,
      543,    0,  539,  567,  533,  536,  548,  544,  533,  533,
      421,  538,    0,  536,  524,  513,  502,  512,  422,  519,
      510,  510,  517,  508,  518,  514,  503,  515,  512,  510,
      501,  527,    0,  507,  496,  492,  497,  502,  489,  504,
      492,  499,  490,  498,  497,  482,  497,  477,  485,  469,
      459,  455,    0,  473,  468,  471,  458,  473,  468,  466,

      464,  459,  450,  449,  464,  459,    0,  445,  449,    0,
      456,  451,    0,  444,  440,  444,  455,  450,  445,  436,
      434,  466,  432,  436,  425,  423,  455,  426,  420,  424,
      418,    0,  422,  416,  448,    0,    0,  418,  411,  410,
      442,    0,  423,    0,  403,  409,  387,    0,  382,  382,
      388,  376,  362,  378,  359,  330,  328,  323,  307,    0,
      303,    0,  254,  231,    0,  222,    0,  238,  205,  174,
      158,  149,  145,   92,    0,  989,  851,  854,  857,  860,
      863,  866,  869,  872,  875,   95,   89,   83,   73,   63,
       18,  878,    4,  881

    } ;

static yyconst flex_int16_t yy_def[595] =
    {   0,
      577,  577,    2,    3,  578,  578,  579,  579,    2,    2,
      580,  580,    2,   13,    2,    2,  581,  581,  582,  582,
        2,    2,  583,  583,    2,    2,  576,  576,  576,  576,
      584,  585,  576,  586,  586,  576,  586,  576,  576,  576,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  587,  587,  587,  588,  588,
      588,  589,  589,  589,  586,   65,  586,  586,  586,  586,
      576,  590,  590,  590,  591,  591,  591,  592,  593,  593,
      593,  594,  576,  584,  576,  585,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,

      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  587,  587,  587,  587,  588,  588,  588,
      588,  589,  589,  589,  589,  586,  586,  586,  586,  586,
      586,  586,  590,  590,  590,  590,  591,  591,  591,  591,
      592,  576,  593,  593,  593,  593,  594,  576,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,

      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,

      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,

      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,

      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,    0,  576,  576,  576,  576,
      576,  576,  576,  576,  576,  576,  576,  576,  576,  576,
      576,  576,  576,  576

    } ;

static yyconst flex_int16_t yy_nxt[1038] =
    {   0,
       28,   29,   30,   31,   32,   33,  153,   35,   36,   37,
       37,   37,   37,  242,   38,   88,   88,   88,   88,   89,
      147,   90,   90,   90,   90,   92,  102,   96,  243,  103,
      108,  104,   93,  100,  193,  101,   97,  116,  105,  117,
      109,   94,   98,  118,  194,  119,   39,   40,   28,   29,
       30,   31,   32,   33,  120,   35,   36,   37,   37,   37,
       37,  111,   38,  113,  112,  143,  114,  115,  121,  122,
      125,  125,  125,  125,  126,  132,  127,  127,  127,  127,
      129,  129,  129,  129,  130,  128,  131,  131,  131,  131,
      185,  124,  186,  123,   39,   40,   41,   87,   42,   43,

      161,   44,   45,  216,  162,   46,   47,   48,  217,   49,
       50,   51,   52,  221,   53,   54,   55,   28,   29,   30,
       31,   32,   33,  264,   57,   36,   58,   58,   58,   58,
      575,   38,  133,  133,  133,  133,  134,  265,  135,  135,
      135,  135,   87,  222,  137,  137,  137,  137,  138,  138,
      138,  138,  139,  183,  140,  140,  140,  140,  144,  144,
      144,  144,  184,   39,   40,   28,   29,   30,   31,   32,
       33,  574,   57,   36,   58,   58,   58,   58,  145,   38,
      146,  146,  146,  146,  148,  148,  148,  148,  149,  573,
      150,  150,  150,  150,  154,  154,  154,  154,  155,  572,

      156,  156,  156,  156,   88,   88,   88,   88,  211,  571,
      212,   39,   40,   28,   29,   30,   31,   32,   33,  306,
       60,   36,   61,   61,   61,   61,  227,   38,   88,   88,
       88,   88,   89,  307,   90,   90,   90,   90,  174,  228,
      188,  175,  189,  570,  569,  190,  125,  125,  125,  125,
      125,  125,  125,  125,  176,  191,  568,  567,  261,   39,
       40,   28,   29,   30,   31,   32,   33,  262,   60,   36,
       61,   61,   61,   61,  126,   38,  127,  127,  127,  127,
      129,  129,  129,  129,  129,  129,  129,  129,  130,  566,
      131,  131,  131,  131,  133,  133,  133,  133,  133,  133,

      133,  133,  138,  138,  138,  138,  383,   39,   40,   28,
       29,   30,   31,   32,   33,  384,   63,   36,   64,   64,
       64,   64,  134,   38,  135,  135,  135,  135,   89,  565,
       90,   90,   90,   90,  198,  138,  138,  138,  138,  139,
      564,  140,  140,  140,  140,  144,  144,  144,  144,  144,
      144,  144,  144,  563,  562,   39,   40,   28,   29,   30,
       31,   32,   33,  561,   63,   36,   64,   64,   64,   64,
      145,   38,  146,  146,  146,  146,  148,  148,  148,  148,
      148,  148,  148,  148,  149,  560,  150,  150,  150,  150,
      154,  154,  154,  154,  154,  154,  154,  154,  252,  282,

      559,  283,  558,   39,   40,   65,   65,   65,   65,  557,
      556,   66,   66,   66,   66,  555,  554,  553,   66,   66,
       66,   66,   66,   66,   67,  253,   68,   68,   68,   68,
      155,  552,  156,  156,  156,  156,  269,  551,  448,  455,
      270,  449,  456,  466,  474,  550,  467,  475,  549,  548,
      547,   69,  546,   70,  545,  544,  543,  542,  541,  540,
      539,  538,  537,   71,   67,  536,   68,   68,   68,   68,
      535,  534,  533,  532,  531,  530,  529,  528,  527,  526,
      525,  524,  523,  522,  521,  520,  519,  518,  517,  516,
      515,   69,  514,   70,  513,  512,  511,  510,  509,  508,

      507,  506,  505,   71,   28,   29,   30,   31,   32,   33,
      504,   73,   36,   74,   74,   74,   74,  503,   38,  502,
      501,  500,  499,  498,  497,  496,  495,  494,  493,  492,
      491,  490,  489,  488,  487,  486,  485,  484,  483,  482,
      481,  480,  479,  478,  477,  476,  473,  472,  471,  470,
       39,   40,   28,   29,   30,   31,   32,   33,  469,   73,
       36,   74,   74,   74,   74,  468,   38,  465,  464,  463,
      462,  461,  460,  459,  458,  457,  454,  453,  452,  451,
      450,  447,  446,  445,  444,  443,  442,  441,  440,  439,
      438,  437,  436,  435,  434,  433,  432,  431,   39,   40,

       28,   29,   30,   31,   32,   33,  430,   76,   36,   77,
       77,   77,   77,  429,   38,  428,  427,  426,  425,  424,
      423,  422,  421,  420,  419,  418,  417,  416,  415,  414,
      413,  412,  411,  410,  409,  408,  407,  406,  405,  404,
      403,  402,  401,  400,  399,  398,   39,   40,   28,   29,
       30,   31,   32,   33,  397,   76,   36,   77,   77,   77,
       77,  396,   38,  395,  394,  393,  392,  391,  390,  389,
      388,  387,  386,  385,  382,  381,  380,  379,  378,  377,
      376,  375,  374,  373,  372,  371,  370,  369,  368,  367,
      366,  365,  364,  363,   39,   40,   28,   29,   30,   31,

       32,   33,  362,   80,   36,   81,   81,   81,   81,  361,
       38,  360,  359,  358,  357,  356,  355,  354,  353,  352,
      351,  350,  349,  348,  347,  346,  345,  344,  343,  342,
      341,  340,  339,  338,  337,  336,  335,  334,  333,  332,
      331,  330,   39,   40,   28,   29,   30,   31,   32,   33,
      329,   80,   36,   81,   81,   81,   81,  328,   38,  327,
      326,  325,  324,  198,  323,  322,  321,  320,  319,  318,
      317,  316,  315,  314,  313,  312,  311,  310,  309,  308,
      305,  304,  303,  302,  301,  300,  299,  298,  297,  296,
       39,   40,   89,  295,  136,  136,  136,  136,  294,  293,

      137,  137,  137,  137,  292,  291,  290,  137,  137,  137,
      137,  137,  137,  241,  241,  241,  241,  289,  288,  241,
      241,  241,  241,  287,  286,  284,  241,  241,  241,  241,
      241,  241,  285,  285,  285,  285,  281,  280,  285,  285,
      285,  285,  279,  278,  277,  285,  285,  285,  285,  285,
      285,   34,   34,   34,   56,   56,   56,   59,   59,   59,
       62,   62,   62,   72,   72,   72,   75,   75,   75,   79,
       79,   79,   84,   84,   84,   86,  276,   86,  151,  151,
      151,  157,  157,  157,  275,  274,  273,  272,  271,  268,
      267,  266,  263,  260,  259,  258,  257,  256,  255,  254,

      251,  250,  249,  248,  247,  246,  245,  244,  240,  239,
      238,  237,  236,  235,  234,  233,  232,  231,  230,  229,
      226,  225,  224,  223,  220,  219,  218,  215,  214,  213,
      210,  209,  208,  207,  206,  205,  204,  203,  202,  201,
      200,  199,  158,  152,  198,  197,  196,  195,  192,  187,
      182,  181,  180,  179,  178,  177,  173,  172,  171,  170,
      169,  168,  167,  166,  165,  164,  163,  160,  159,   85,
       83,  158,  152,  142,  141,  110,  107,  106,   99,   95,
       91,   85,   83,  576,   82,   82,   78,   78,   27,  576,
      576,  576,  576,  576,  576,  576,  576,  576,  576,  576,

      576,  576,  576,  576,  576,  576,  576,  576,  576,  576,
      576,  576,  576,  576,  576,  576,  576,  576,  576,  576,
      576,  576,  576,  576,  576,  576,  576,  576,  576,  576,
      576,  576,  576,  576,  576,  576,  576
    } ;

static yyconst flex_int16_t yy_chk[1038] =
    {   0,
        1,    1,    1,    1,    1,    1,  593,    1,    1,    1,
        1,    1,    1,  199,    1,   35,   35,   35,   35,   37,
      591,   37,   37,   37,   37,   42,   47,   44,  199,   47,
       50,   47,   42,   46,  117,   46,   44,   54,   47,   54,
       50,   42,   44,   54,  117,   54,    1,    1,    2,    2,
        2,    2,    2,    2,   54,    2,    2,    2,    2,    2,
        2,   52,    2,   53,   52,  590,   53,   53,   55,   55,
       57,   57,   57,   57,   58,  589,   58,   58,   58,   58,
       60,   60,   60,   60,   61,  588,   61,   61,   61,   61,
      113,  587,  113,   55,    2,    2,    3,  586,    3,    3,

       93,    3,    3,  175,   93,    3,    3,    3,  175,    3,
        3,    3,    3,  179,    3,    3,    3,    5,    5,    5,
        5,    5,    5,  221,    5,    5,    5,    5,    5,    5,
      574,    5,   63,   63,   63,   63,   64,  221,   64,   64,
       64,   64,   66,  179,   66,   66,   66,   66,   67,   67,
       67,   67,   68,  112,   68,   68,   68,   68,   73,   73,
       73,   73,  112,    5,    5,    6,    6,    6,    6,    6,
        6,  573,    6,    6,    6,    6,    6,    6,   74,    6,
       74,   74,   74,   74,   76,   76,   76,   76,   77,  572,
       77,   77,   77,   77,   80,   80,   80,   80,   81,  571,

       81,   81,   81,   81,   88,   88,   88,   88,  171,  570,
      171,    6,    6,    7,    7,    7,    7,    7,    7,  266,
        7,    7,    7,    7,    7,    7,  184,    7,   89,   89,
       89,   89,   90,  266,   90,   90,   90,   90,  105,  184,
      115,  105,  115,  569,  568,  115,  125,  125,  125,  125,
      126,  126,  126,  126,  105,  115,  566,  564,  219,    7,
        7,    8,    8,    8,    8,    8,    8,  219,    8,    8,
        8,    8,    8,    8,  127,    8,  127,  127,  127,  127,
      129,  129,  129,  129,  130,  130,  130,  130,  131,  563,
      131,  131,  131,  131,  133,  133,  133,  133,  134,  134,

      134,  134,  138,  138,  138,  138,  358,    8,    8,   11,
       11,   11,   11,   11,   11,  358,   11,   11,   11,   11,
       11,   11,  135,   11,  135,  135,  135,  135,  136,  561,
      136,  136,  136,  136,  136,  139,  139,  139,  139,  140,
      559,  140,  140,  140,  140,  144,  144,  144,  144,  145,
      145,  145,  145,  558,  557,   11,   11,   12,   12,   12,
       12,   12,   12,  556,   12,   12,   12,   12,   12,   12,
      146,   12,  146,  146,  146,  146,  148,  148,  148,  148,
      149,  149,  149,  149,  150,  555,  150,  150,  150,  150,
      154,  154,  154,  154,  155,  155,  155,  155,  209,  239,

      554,  239,  553,   12,   12,   13,   13,   13,   13,  552,
      551,   13,   13,   13,   13,  550,  549,  547,   13,   13,
       13,   13,   13,   13,   15,  209,   15,   15,   15,   15,
      156,  546,  156,  156,  156,  156,  226,  545,  432,  440,
      226,  432,  440,  451,  459,  543,  451,  459,  541,  540,
      539,   15,  538,   15,  535,  534,  533,  531,  530,  529,
      528,  527,  526,   15,   16,  525,   16,   16,   16,   16,
      524,  523,  522,  521,  520,  519,  518,  517,  516,  515,
      514,  512,  511,  509,  508,  506,  505,  504,  503,  502,
      501,   16,  500,   16,  499,  498,  497,  496,  495,  494,

      492,  491,  490,   16,   17,   17,   17,   17,   17,   17,
      489,   17,   17,   17,   17,   17,   17,  488,   17,  487,
      486,  485,  484,  483,  482,  481,  480,  479,  478,  477,
      476,  475,  474,  472,  471,  470,  469,  468,  467,  466,
      465,  464,  463,  462,  461,  460,  458,  457,  456,  455,
       17,   17,   18,   18,   18,   18,   18,   18,  454,   18,
       18,   18,   18,   18,   18,  452,   18,  450,  449,  448,
      447,  446,  445,  444,  443,  441,  438,  437,  436,  434,
      433,  431,  429,  428,  427,  426,  425,  424,  423,  422,
      421,  420,  419,  417,  416,  415,  414,  413,   18,   18,

       19,   19,   19,   19,   19,   19,  412,   19,   19,   19,
       19,   19,   19,  411,   19,  410,  408,  407,  406,  405,
      403,  402,  401,  400,  399,  398,  397,  396,  395,  394,
      393,  392,  390,  389,  388,  387,  386,  384,  383,  382,
      381,  380,  379,  378,  376,  375,   19,   19,   20,   20,
       20,   20,   20,   20,  374,   20,   20,   20,   20,   20,
       20,  373,   20,  372,  371,  370,  369,  368,  367,  363,
      362,  361,  360,  359,  356,  354,  352,  351,  350,  349,
      347,  346,  345,  344,  343,  342,  341,  340,  338,  337,
      336,  334,  332,  331,   20,   20,   23,   23,   23,   23,

       23,   23,  330,   23,   23,   23,   23,   23,   23,  329,
       23,  328,  327,  326,  324,  323,  322,  320,  317,  316,
      315,  314,  313,  312,  311,  310,  308,  307,  306,  305,
      304,  303,  302,  301,  300,  299,  298,  297,  296,  295,
      293,  292,   23,   23,   24,   24,   24,   24,   24,   24,
      291,   24,   24,   24,   24,   24,   24,  290,   24,  289,
      288,  287,  286,  285,  284,  283,  282,  281,  280,  279,
      278,  277,  276,  274,  272,  271,  270,  269,  268,  267,
      265,  264,  263,  262,  260,  259,  258,  257,  256,  253,
       24,   24,   65,  252,   65,   65,   65,   65,  251,  250,

       65,   65,   65,   65,  249,  248,  247,   65,   65,   65,
       65,   65,   65,  198,  198,  198,  198,  245,  244,  198,
      198,  198,  198,  243,  242,  240,  198,  198,  198,  198,
      198,  198,  241,  241,  241,  241,  238,  236,  241,  241,
      241,  241,  235,  234,  233,  241,  241,  241,  241,  241,
      241,  577,  577,  577,  578,  578,  578,  579,  579,  579,
      580,  580,  580,  581,  581,  581,  582,  582,  582,  583,
      583,  583,  584,  584,  584,  585,  232,  585,  592,  592,
      592,  594,  594,  594,  231,  230,  229,  228,  227,  224,
      223,  222,  220,  218,  217,  216,  215,  213,  212,  211,

      208,  206,  205,  204,  203,  202,  201,  200,  197,  196,
      195,  194,  193,  192,  191,  190,  189,  188,  186,  185,
      183,  182,  181,  180,  178,  177,  176,  174,  173,  172,
      170,  169,  168,  167,  166,  165,  164,  163,  162,  161,
      160,  159,  157,  151,  137,  120,  119,  118,  116,  114,
      111,  110,  109,  108,  107,  106,  104,  103,  102,  101,
      100,   99,   98,   97,   96,   95,   94,   92,   91,   84,
       83,   82,   78,   70,   69,   51,   49,   48,   45,   43,
       41,   31,   29,   27,   26,   25,   22,   21,  576,  576,
      576,  576,  576,  576,  576,  576,  576,  576,  576,  576,

      576,  576,  576,  576,  576,  576,  576,  576,  576,  576,
      576,  576,  576,  576,  576,  576,  576,  576,  576,  576,
      576,  576,  576,  576,  576,  576,  576,  576,  576,  576,
      576,  576,  576,  576,  576,  576,  576
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "cftoken.l"
/*	$KAME: cftoken.l,v 1.35 2005/01/12 06:06:11 suz Exp $	*/
#line 4 "cftoken.l"
/*
 * Copyright (C) 2002 WIDE Project.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 3. Neither the name of the project nor the names of its contributors
 *    may be used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE PROJECT AND CONTRIBUTORS ``AS IS'' AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE PROJECT OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */
#include <sys/types.h>
#include <sys/param.h>
#include <sys/socket.h>
#include <sys/queue.h>
#include <sys/time.h>

#include <netinet/in.h>

#include <errno.h>
#include <syslog.h>
#include <string.h>
#ifdef HAVE_STDARG_H
#include <stdarg.h>
#else
#include <varargs.h>
#endif

#include "dhcp6.h"
#include "config.h"
#include "common.h"
#include "y.tab.h"

#define YY_NO_UNPUT 1

char *configfilename;
int lineno = 1;


/* Recursion limit for includes */
#define MAX_INCLUDE_DEPTH 10

static struct include_stack {
	char *path;
	YY_BUFFER_STATE state;
	int lineno;
} incstack[MAX_INCLUDE_DEPTH];
int incstackp = 0;


static int yy_first_time = 1;
static int yyerrorcount = 0;
 
#ifndef NOCONFIG_DEBUG
#define YYDEBUG 1

int cfdebug = 1;
#else
int cfdebug = 0;
#endif

extern int yyparse __P((void));
extern int cf_post_config __P((void));

static void cfdebug_print __P((char *, char *, int));

#define DP(str) if (cfdebug) cfdebug_print(str, yytext, yyleng)
#define DECHO if (cfdebug) cfdebug_print(NULL, yytext, yyleng);
#define DNOECHO if (cfdebug) cfdebug_print(NULL, "****", yyleng);
/* abbreviations */












#line 981 "lex.yy.c"

#define INITIAL 0
#define S_CNF 1
#define S_IFACE 2
#define S_PROFILE 3
#define S_PREF 4
#define S_HOST 5
#define S_DUID 6
#define S_IA 7
#define S_AUTH 8
#define S_KEY 9
#define S_SECRET 10
#define S_ADDRPOOL 11
#define S_INCL 12

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 125 "cftoken.l"


	if (yy_first_time) {
		BEGIN S_CNF;
		yy_first_time = 0;
	}

	/* interface configuration */
#line 1189 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 577 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 989 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 133 "cftoken.l"
{ DECHO; BEGIN S_IFACE; return (INTERFACE); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 134 "cftoken.l"
{
	DECHO;
	yylval.str = strdup(yytext);
	BEGIN S_CNF;
	return (IFNAME);
}
	YY_BREAK
/* profile configuration */
case 3:
YY_RULE_SETUP
#line 142 "cftoken.l"
{ DECHO; BEGIN S_PROFILE; return (PROFILE); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 143 "cftoken.l"
{
	DECHO;
	yylval.str = strdup(yytext);
	BEGIN S_CNF;
	return (PROFILENAME);
}
	YY_BREAK
/* host configuration */
case 5:
YY_RULE_SETUP
#line 151 "cftoken.l"
{ DECHO; BEGIN S_HOST; return (HOST); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 152 "cftoken.l"
{
	DECHO;
	yylval.str = strdup(yytext);
	BEGIN S_CNF;
	return (HOSTNAME);
}
	YY_BREAK
/* address pool configuration */
case 7:
YY_RULE_SETUP
#line 160 "cftoken.l"
{ DECHO; BEGIN S_ADDRPOOL; return (ADDRPOOL); }  
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 162 "cftoken.l"
{
	DECHO;
	yylval.str = strdup(yytext);
	BEGIN S_CNF;
	return (POOLNAME);
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 169 "cftoken.l"
{ DECHO; BEGIN S_DUID; return (DUID); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 170 "cftoken.l"
{
	DECHO;
	yylval.str = strdup(yytext);
	BEGIN S_CNF;
	return (DUID_ID);
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 177 "cftoken.l"
{ DECHO; return (ADDRESS); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 179 "cftoken.l"
{ DECHO; return (PREFIX); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 181 "cftoken.l"
{ DECHO; return (PREFERENCE); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 183 "cftoken.l"
{ DECHO; return (SCRIPT); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 185 "cftoken.l"
{ DECHO; return (DELAYEDKEY); }
	YY_BREAK
/* request */
case 16:
YY_RULE_SETUP
#line 188 "cftoken.l"
{ DECHO; return (REQUEST); }
	YY_BREAK
/* send */
case 17:
YY_RULE_SETUP
#line 191 "cftoken.l"
{ DECHO; return (SEND); }
	YY_BREAK
/* range */
case 18:
YY_RULE_SETUP
#line 194 "cftoken.l"
{ DECHO; return (RANGE); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 195 "cftoken.l"
{ DECHO; return (TO); }
	YY_BREAK
/* address-pool */
case 20:
YY_RULE_SETUP
#line 198 "cftoken.l"
{ DECHO; return (ADDRESS_POOL); }
	YY_BREAK
/* DHCP options */
case 21:
YY_RULE_SETUP
#line 201 "cftoken.l"
{ DECHO; return (OPTION); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 203 "cftoken.l"
{ DECHO; return (RAPID_COMMIT); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 204 "cftoken.l"
{ DECHO; return (IA_PD); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 205 "cftoken.l"
{ DECHO; return (IA_NA); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 206 "cftoken.l"
{ DECHO; return (DNS_SERVERS); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 207 "cftoken.l"
{ DECHO; return (DNS_NAME); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 208 "cftoken.l"
{ DECHO; return (SIP_SERVERS); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 209 "cftoken.l"
{ DECHO; return (SIP_NAME); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 210 "cftoken.l"
{ DECHO; return (NTP_SERVERS); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 211 "cftoken.l"
{ DECHO; return (NIS_SERVERS); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 212 "cftoken.l"
{ DECHO; return (NIS_NAME); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 213 "cftoken.l"
{ DECHO; return (NISP_SERVERS); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 214 "cftoken.l"
{ DECHO; return (NISP_NAME); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 215 "cftoken.l"
{ DECHO; return (BCMCS_SERVERS); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 216 "cftoken.l"
{ DECHO; return (BCMCS_NAME); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 217 "cftoken.l"
{ DECHO; return (REFRESHTIME); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 218 "cftoken.l"
{ DECHO; return (RECONFIGURE_ACCEPT); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 219 "cftoken.l"
{ DECHO; return (AFTR_SERVERS); }
	YY_BREAK
/* provided for a backward compatibility to WIDE-DHCPv6 before Oct 1 2006 */
case 39:
YY_RULE_SETUP
#line 222 "cftoken.l"
{ DECHO; return (NIS_NAME); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 223 "cftoken.l"
{ DECHO; return (NISP_NAME); }	
	YY_BREAK
/* generic options */
case 41:
YY_RULE_SETUP
#line 226 "cftoken.l"
{ DECHO; return (INFO_ONLY); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 228 "cftoken.l"
{ DECHO; return (ALLOW); }
	YY_BREAK
/* identity association */
case 43:
YY_RULE_SETUP
#line 231 "cftoken.l"
{ DECHO; BEGIN S_IA; return(ID_ASSOC); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 232 "cftoken.l"
{ DECHO; return(IA_PD); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 233 "cftoken.l"
{ DECHO; return(IA_NA); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 234 "cftoken.l"
{ DECHO; yylval.str = strdup(yytext); return(IAID); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 235 "cftoken.l"
{ DP("begin of closure"); BEGIN S_CNF; return (BCL); }
	YY_BREAK
/* t1 and t2 */
case 48:
YY_RULE_SETUP
#line 238 "cftoken.l"
{ DECHO; return(T1); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 239 "cftoken.l"
{ DECHO; return(T2); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 240 "cftoken.l"
{ DECHO; return(SUGGEST_T); }
	YY_BREAK
/*
	 * interface parameters for delegated prefix configuration.
	 * when lex reads an interface name, the state will be back to
	 * S_CNF.
	 */
case 51:
YY_RULE_SETUP
#line 246 "cftoken.l"
{ DECHO; BEGIN S_IFACE; return (PREFIX_INTERFACE); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 247 "cftoken.l"
{ DECHO; return (SLA_ID); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 248 "cftoken.l"
{ DECHO; return (SLA_LEN); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 249 "cftoken.l"
{ DECHO; return (IFID); }
	YY_BREAK
/* duration */
case 55:
YY_RULE_SETUP
#line 252 "cftoken.l"
{ DECHO; return (INFINITY); }
	YY_BREAK
/* authentication option */
case 56:
YY_RULE_SETUP
#line 255 "cftoken.l"
{ DECHO; BEGIN S_AUTH; return (AUTHENTICATION); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 256 "cftoken.l"
{
	DECHO;
	yylval.str = strdup(yytext);
	BEGIN S_CNF;
	return (AUTHNAME);
}
	YY_BREAK
/* authentication parameters */
case 58:
YY_RULE_SETUP
#line 264 "cftoken.l"
{ DECHO; return (PROTOCOL); };
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 265 "cftoken.l"
{ DECHO; return (ALGORITHM); };
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 266 "cftoken.l"
{ DECHO; return (RDM); };
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 267 "cftoken.l"
{ DECHO; return (KEY); };
	YY_BREAK
/* authentication protocols */
case 62:
YY_RULE_SETUP
#line 270 "cftoken.l"
{ DECHO; return (DELAYED); };
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 271 "cftoken.l"
{ DECHO; return (RECONFIG); };
	YY_BREAK
/* authentication algorithms */
case 64:
YY_RULE_SETUP
#line 274 "cftoken.l"
{ DECHO; return (HMACMD5); };
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 275 "cftoken.l"
{ DECHO; return (HMACMD5); };
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 276 "cftoken.l"
{ DECHO; return (HMACMD5); };
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 277 "cftoken.l"
{ DECHO; return (HMACMD5); };
	YY_BREAK
/* authentication RDM */
case 68:
YY_RULE_SETUP
#line 280 "cftoken.l"
{ DECHO; return (MONOCOUNTER); };
	YY_BREAK
/* secret keys */
case 69:
YY_RULE_SETUP
#line 283 "cftoken.l"
{ DECHO; BEGIN S_KEY; return (KEYINFO); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 284 "cftoken.l"
{
	DECHO;
	yylval.str = strdup(yytext);
	BEGIN S_CNF;
	return (KEYNAME);
}
	YY_BREAK
/* key parameters */
case 71:
YY_RULE_SETUP
#line 292 "cftoken.l"
{ DECHO; return (REALM); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 293 "cftoken.l"
{ DECHO; return (KEYID); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 294 "cftoken.l"
{ DECHO; BEGIN S_SECRET; return (SECRET); }
	YY_BREAK
case 74:
/* rule 74 can match eol */
YY_RULE_SETUP
#line 295 "cftoken.l"
{
	DNOECHO;
	yylval.str = strdup(yytext);
	BEGIN S_CNF;
	return (QSTRING);
}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 301 "cftoken.l"
{ DECHO; return (EXPIRE); }
	YY_BREAK
/* include */
case 76:
YY_RULE_SETUP
#line 304 "cftoken.l"
{ DECHO; BEGIN S_INCL; return (INCLUDE); }
	YY_BREAK
case 77:
/* rule 77 can match eol */
YY_RULE_SETUP
#line 305 "cftoken.l"
{
	DECHO;
	yylval.str = strdup(yytext);
	BEGIN S_CNF;
	return (QSTRING);
}
	YY_BREAK
/* quoted string */
case 78:
/* rule 78 can match eol */
YY_RULE_SETUP
#line 313 "cftoken.l"
{
		DECHO;
		yylval.str = strdup(yytext);
		return (QSTRING);
	}
	YY_BREAK
/* misc */
case 79:
YY_RULE_SETUP
#line 320 "cftoken.l"
{ ; }
	YY_BREAK
case 80:
/* rule 80 can match eol */
YY_RULE_SETUP
#line 321 "cftoken.l"
{ lineno++; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 322 "cftoken.l"
{ DP("comment"); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 323 "cftoken.l"
{
	DECHO;
	yylval.num = strtoll(yytext, NULL, 10);
	return (NUMBER);
}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 328 "cftoken.l"
{ DECHO; return (SLASH); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 329 "cftoken.l"
{ DECHO; return (COMMA); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 330 "cftoken.l"
{ DP("end of sentence"); return (EOS); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 331 "cftoken.l"
{ DP("begin of closure"); return (BCL); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 332 "cftoken.l"
{ DP("end of closure"); return (ECL); }
	YY_BREAK
/* generic string */
case 88:
YY_RULE_SETUP
#line 335 "cftoken.l"
{
		DECHO;
		yylval.str = strdup(yytext);
		return (STRING);
	}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(S_CNF):
case YY_STATE_EOF(S_IFACE):
case YY_STATE_EOF(S_PROFILE):
case YY_STATE_EOF(S_PREF):
case YY_STATE_EOF(S_HOST):
case YY_STATE_EOF(S_DUID):
case YY_STATE_EOF(S_IA):
case YY_STATE_EOF(S_AUTH):
case YY_STATE_EOF(S_KEY):
case YY_STATE_EOF(S_SECRET):
case YY_STATE_EOF(S_ADDRPOOL):
case YY_STATE_EOF(S_INCL):
#line 341 "cftoken.l"
{
		if (--incstackp < 0)
			yyterminate();
		else {
			yy_delete_buffer(YY_CURRENT_BUFFER);
			free(incstack[incstackp + 1].path);
			configfilename = incstack[incstackp].path;
			lineno = incstack[incstackp].lineno;
			yy_switch_to_buffer(incstack[incstackp].state);
		}
	}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 353 "cftoken.l"
ECHO;
	YY_BREAK
#line 1833 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 577 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 577 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 576);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 353 "cftoken.l"


static void
cfdebug_print(w, t, l)
	char *w, *t;
	int l;
{
	if (w) {
		dprintf_rtk(LOG_DEBUG, FNAME,
		    "<%d>%s [%s] (%d)", yy_start, w, t, l);
	} else {
		dprintf_rtk(LOG_DEBUG, FNAME,
		    "<%d>[%s] (%d)", yy_start, t, l);
	}
}

static void
yyerror0(int level, char *s, va_list ap)
{
	char ebuf[BUFSIZ], *bp, *ep;

	bp = ebuf;
	ep = ebuf + sizeof(ebuf);
	bp += snprintf(bp, ep - bp, "%s %d: ", configfilename, lineno);
	if (bp < ep)
		bp += vsnprintf(bp, ep - bp, s, ap);

	dprintf_rtk(level, FNAME, ebuf);
}

void
yyerror(char *s, ...)
{
	va_list ap;
#ifdef HAVE_STDARG_H
	va_start(ap, s);
#else
	va_start(ap);
#endif
	yyerror0(LOG_ERR, s, ap);
	va_end(ap);
	yyerrorcount++;
}

void
yywarn(char *s, ...)
{
	va_list ap;
#ifdef HAVE_STDARG_H
	va_start(ap, s);
#else
	va_start(ap);
#endif
	yyerror0(LOG_WARNING, s, ap);
	va_end(ap);
}

int
cfswitch_buffer(incl)
	char *incl;
{
	char *path = qstrdup(incl);
	FILE *fp;

	if (incstackp >= MAX_INCLUDE_DEPTH) {
		dprintf_rtk(LOG_ERR, FNAME, "cfparse: includes nested too deeply");
		return (-1);
	}
	incstack[incstackp].path = configfilename;
	incstack[incstackp].state = YY_CURRENT_BUFFER;
	incstack[incstackp].lineno = lineno;

	fp = fopen(path, "r");
	if (fp == NULL) {
		dprintf_rtk(LOG_ERR, FNAME, "cfparse: fopen(%s): %s",
			path, strerror(errno));
		if (errno == ENOENT)
			return (0);
		return (-1);
	}
	incstackp++;
	configfilename = path;
	lineno = 1;
	yy_switch_to_buffer(yy_create_buffer(fp,YY_BUF_SIZE));

	BEGIN(S_CNF);

	return (0);
}

int
cfparse(conf)
	char *conf;
{
	configfilename = conf;
	if ((yyin = fopen(configfilename, "r")) == NULL) {
		dprintf_rtk(LOG_ERR, FNAME, "cfparse: fopen(%s): %s",
			configfilename, strerror(errno));
		if (errno == ENOENT)
			return (0);
		return (-1);
	}

	if (yyparse() || yyerrorcount) {
		if (yyerrorcount) {
			yyerror("fatal parse failure: exiting (%d errors)",
				yyerrorcount);
		} else
			yyerror("fatal parse failure: exiting");
		return (-1);
	}

	return (cf_post_config());
}

