/* version.c */
/* Autogenerated by Makefile - DO NOT EDIT */

#include "version.h"
const char *version_string = "1.19";
const char *compilation_string = "msdk-linux-gcc -DHAVE_CONFIG_H -DSYSTEM_WGETRC=\"/usr/local/etc/wgetrc\" -DLOCALEDIR=\"/usr/local/share/locale\" -I. -I../lib -I../lib -I/data/xiaoning/RealTek/HN120/users/lib/include -I/data/xiaoning/RealTek/HN120/users/openssl-1.0.2d/include/ -DHAVE_LIBSSL -I/data/xiaoning/RealTek/HN120/users/zlib-1.2.5 -DNDEBUG -I/data/xiaoning/RealTek/HN120/users/libiconv-1.14/include";
const char *link_string = "msdk-linux-gcc -I/data/xiaoning/RealTek/HN120/users/openssl-1.0.2d/include/ -DHAVE_LIBSSL -I/data/xiaoning/RealTek/HN120/users/zlib-1.2.5 -DNDEBUG -I/data/xiaoning/RealTek/HN120/users/libiconv-1.14/include -liconv -L/data/xiaoning/RealTek/HN120/users/lib/lib -L/data/xiaoning/RealTek/HN120/users/openssl-1.0.2d/ -lssl -lcrypto -L/data/xiaoning/RealTek/HN120/users/zlib-1.2.5 -lz ftp-opie.o openssl.o http-ntlm.o ../lib/libgnu.a -lrt -L/data/xiaoning/RealTek/HN120/users/lib/lib -liconv ";
