#ifndef __MESSAGE_H__
#define __MESSAGE_H__

/* BASE */
#define MSG_GET_INITINFO							"MSG_GET_INITINFO"
#define MSG_WTP_ABILITY_NOTIFY						"MSG_WTP_ABILITY_NOTIFY"
#define MSG_WTP_GET_ROUTE_OVERVIEW					"MSG_WTP_GET_ROUTE_OVERVIEW"
#define MSG_WTP_GET_DEVICE_WIFI_INFO_NEW			"MSG_WTP_GET_DEVICE_WIFI_INFO_NEW"
#define MSG_WTP_SET_DEVICE_WIFI_NEW					"MSG_WTP_SET_DEVICE_WIFI_NEW"
#define MSG_WTP_GET_BROADBAND_SETTING				"MSG_WTP_GET_BROADBAND_SETTING"
#define MSG_WTP_SET_BROADBAND_SETTING				"MSG_WTP_SET_BROADBAND_SETTING"
#define MSG_WTP_WIFI_ACCELERATE						"MSG_WTP_WIFI_ACCELERATE"
#define MSG_WTP_DEVICE_OPERATE						"MSG_WTP_DEVICE_OPERATE"
#define MSG_WTP_DEVICE_STATUS_CHANG					"MSG_WTP_DEVICE_STATUS_CHANG"
#define MSG_GET_DEVUPDATE_INFO						"MSG_GET_DEVUPDATE_INFO"
#define MSG_SEND_DEVUPDATE							"MSG_SEND_DEVUPDATE"
#define MSG_WTP_GET_CLIENT_ACCESS_CONTROL_INFO		"MSG_WTP_GET_CLIENT_ACCESS_CONTROL_INFO"
#define MSG_WTP_SET_CLIENT_ACCESS_CONTROL			"MSG_WTP_SET_CLIENT_ACCESS_CONTROL"
#define MSG_WTP_SET_QOS								"MSG_WTP_SET_QOS"
#define MSG_WTP_GET_ROUTE_BASE_INFO					"MSG_WTP_GET_ROUTE_BASE_INFO"
#define MSG_WTP_LOG_UPLOAD							"MSG_WTP_LOG_UPLOAD"
#define MSG_GET_DEVICE_PASSWORD						"MSG_GET_DEVICE_PASSWORD"
#define MSG_GET_DEVICE_INFO							"MSG_GET_DEVICE_INFO"
/* repeator add */
#define MSG_WTP_GET_DEVICE_WIFI_INFO				"MSG_WTP_GET_DEVICE_WIFI_INFO"
#define MSG_WTP_SET_DEVICE_WIFI						"MSG_WTP_SET_DEVICE_WIFI"
#define MSG_WTP_SCAN_DEVICES						"MSG_WTP_SCAN_DEVICES"
#define WTP_ONLINE_NOTIFICATION_REQ					"WTP_ONLINE_NOTIFICATION_REQ"
#define MSG_AP_GET_WIFI_SWITCH_STATUS				"MSG_AP_GET_WIFI_SWITCH_STATUS"


/*request*/
#define MSG_GET_INITINFO_REQ						"MSG_GET_INITINFO_REQ"
#define MSG_WTP_ABILITY_NOTIFY_REQ					"MSG_WTP_ABILITY_NOTIFY_REQ"
#define MSG_WTP_GET_ROUTE_OVERVIEW_REQ				"MSG_WTP_GET_ROUTE_OVERVIEW_REQ"
#define MSG_WTP_GET_DEVICE_WIFI_INFO_NEW_REQ		"MSG_WTP_GET_DEVICE_WIFI_INFO_NEW_REQ"
#define MSG_WTP_SET_DEVICE_WIFI_NEW_REQ				"MSG_WTP_SET_DEVICE_WIFI_NEW_REQ"
#define MSG_WTP_GET_BROADBAND_SETTING_REQ			"MSG_WTP_GET_BROADBAND_SETTING_REQ"
#define MSG_WTP_SET_BROADBAND_SETTING_REQ			"MSG_WTP_SET_BROADBAND_SETTING_REQ"
#define MSG_WTP_WIFI_ACCELERATE_REQ					"MSG_WTP_WIFI_ACCELERATE_REQ"
#define MSG_WTP_DEVICE_OPERATE_REQ					"MSG_WTP_DEVICE_OPERATE_REQ"
#define MSG_WTP_DEVICE_STATUS_CHANG_REQ				"MSG_WTP_DEVICE_STATUS_CHANG_REQ"
#define MSG_GET_DEVUPDATE_INFO_REQ					"MSG_GET_DEVUPDATE_INFO_REQ"
#define MSG_SEND_DEVUPDATE_REQ						"MSG_SEND_DEVUPDATE_REQ"
#define MSG_WTP_GET_CLIENT_ACCESS_CONTROL_INFO_REQ	"MSG_WTP_GET_CLIENT_ACCESS_CONTROL_INFO_REQ"
#define MSG_WTP_SET_CLIENT_ACCESS_CONTROL_REQ		"MSG_WTP_SET_CLIENT_ACCESS_CONTROL_REQ"
#define MSG_WTP_SET_QOS_REQ							"MSG_WTP_SET_QOS_REQ"
#define MSG_WTP_GET_ROUTE_BASE_INFO_REQ				"MSG_WTP_GET_ROUTE_BASE_INFO_REQ"
#define MSG_WTP_LOG_UPLOAD_REQ						"MSG_WTP_LOG_UPLOAD_REQ"

/* repeator add */
#define MSG_WTP_GET_DEVICE_WIFI_INFO_REQ			"MSG_WTP_GET_DEVICE_WIFI_INFO_REQ"
#define MSG_WTP_SET_DEVICE_WIFI_REQ					"MSG_WTP_SET_DEVICE_WIFI_REQ"
#define MSG_AP_GET_WIFI_SWITCH_STATUS_REQ			"MSG_AP_GET_WIFI_SWITCH_STATUS_REQ"

/* response */
#define MSG_GET_INITINFO_RSP						"MSG_GET_INITINFO_RSP"
#define MSG_WTP_ABILITY_NOTIFY_RSP					"MSG_WTP_ABILITY_NOTIFY_RSP"
#define MSG_WTP_GET_ROUTE_OVERVIEW_RSP				"MSG_WTP_GET_ROUTE_OVERVIEW_RSP"
#define MSG_WTP_GET_DEVICE_WIFI_INFO_NEW_RSP		"MSG_WTP_GET_DEVICE_WIFI_INFO_NEW_RSP"
#define MSG_WTP_SET_DEVICE_WIFI_NEW_RSP				"MSG_WTP_SET_DEVICE_WIFI_NEW_RSP"
#define MSG_WTP_GET_BROADBAND_SETTING_RSP			"MSG_WTP_GET_BROADBAND_SETTING_RSP"
#define MSG_WTP_SET_BROADBAND_SETTING_RSP			"MSG_WTP_SET_BROADBAND_SETTING_RSP"
#define MSG_WTP_WIFI_ACCELERATE_RSP					"MSG_WTP_WIFI_ACCELERATE_RSP"
#define MSG_WTP_DEVICE_OPERATE_RSP					"MSG_WTP_DEVICE_OPERATE_RSP"
#define MSG_WTP_DEVICE_STATUS_CHANG_RSP				"MSG_WTP_DEVICE_STATUS_CHANG_RSP"
#define MSG_GET_DEVUPDATE_INFO_RSP					"MSG_GET_DEVUPDATE_INFO_RSP"
#define MSG_SEND_DEVUPDATE_RSP						"MSG_SEND_DEVUPDATE_RSP"
#define MSG_WTP_GET_CLIENT_ACCESS_CONTROL_INFO_RSP	"MSG_WTP_GET_CLIENT_ACCESS_CONTROL_INFO_RSP"
#define MSG_WTP_SET_CLIENT_ACCESS_CONTROL_RSP		"MSG_WTP_SET_CLIENT_ACCESS_CONTROL_RSP"
#define MSG_WTP_SET_QOS_RSP							"MSG_WTP_SET_QOS_RSP"
#define MSG_WTP_GET_ROUTE_BASE_INFO_RSP				"MSG_WTP_GET_ROUTE_BASE_INFO_RSP"
#define MSG_WTP_LOG_UPLOAD_RSP						"MSG_WTP_LOG_UPLOAD_RSP"

/* repeator add */
#define MSG_WTP_GET_DEVICE_WIFI_INFO_RSP			"MSG_WTP_GET_DEVICE_WIFI_INFO_RSP"
#define MSG_WTP_SET_DEVICE_WIFI_RSP					"MSG_WTP_SET_DEVICE_WIFI_RSP"
#define MSG_AP_GET_WIFI_SWITCH_STATUS_RSP			"MSG_AP_GET_WIFI_SWITCH_STATUS_RSP"


/* req from app */
#define MSG_GET_DEVICE_PASSWORD_REQ					"MSG_GET_DEVICE_PASSWORD_REQ"
#define MSG_GET_DEVICE_INFO_REQ						"MSG_GET_DEVICE_INFO_REQ"
#define MSG_WTP_SCAN_DEVICES_REQ					"MSG_WTP_SCAN_DEVICES_REQ"
#define MSG_WTP_ONLINE_NOTIFICATION_REQ				"MSG_WTP_ONLINE_NOTIFICATION_REQ"

/* rsp to app */
#define MSG_GET_DEVICE_PASSWORD_RSP					"MSG_GET_DEVICE_PASSWORD_RSP"
#define MSG_GET_DEVICE_INFO_RSP						"MSG_GET_DEVICE_INFO_RSP" 

#endif
