#ifndef MK1MF_BUILD
  /* auto-generated by crypto/Makefile for crypto/cversion.c */
  #define CFLAGS "msdk-linux-gcc -DDSO_DLFCN -DHAVE_DLFCN_H -DTERMIO -Os -fomit-frame-pointer -Wall"
  #define PLATFORM "mips-linux"
  #define DATE "Mon Apr 29 09:40:54 CST 2019"
#endif
